[phases.setup]
nixPkgs = ["python312", "libuuid"]

[phases.install]
cmds = ["pip install -r requirements.txt"]
[build]
dependencies = [
  "libuuid1"
]

[phases.setup]
aptPkgs = ["git", "ffmpeg"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]


